title: David Li
logo: /images/logo.png
description: >
  BS Mechanical Engineering (Mechatronics)
  <br>
  MS Electrical Engineering (Control Systems)
  <br><br>
  <a href="https://www.linkedin.com/in/davecyli/">LinkedIn</a>

theme: jekyll-theme-minimal
